---
- name: install uStreamer
  import_tasks: ustreamer.yml
  tags:
    - ustreamer

- name: install nginx
  import_tasks: nginx.yml

- name: install HID USB gadget
  import_tasks: install_usb_gadget.yml

- name: collect BasslineMnk required apt packages on all systems
  set_fact:
    basslinemnk_packages:
      - git
      - python3-venv
      - sudo

- name: collect Debian and Ubuntu specific BasslineMnk required apt packages
  set_fact:
    basslinemnk_packages: "{{ basslinemnk_packages }} + ['python-pip']"
  when: ansible_distribution == 'Debian' or (ansible_distribution == 'Ubuntu' and ansible_distribution_version != '20.04')

- name: collect Ubuntu 20.04 specific BasslineMnk required apt packages
  set_fact:
    basslinemnk_packages: "{{ basslinemnk_packages }} + ['python3-pip']"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: install BasslineMnk pre-requisite packages
  apt:
    name: "{{ basslinemnk_packages }}"
    state: present

- name: create basslinemnk group
  group:
    name: "{{ basslinemnk_group }}"
    state: present

- name: create basslinemnk user
  user:
    name: "{{ basslinemnk_user }}"
    group: "{{ basslinemnk_group }}"
    system: yes
    create_home: yes

- name: copy admin scripts
  copy:
    src: "{{ item }}"
    dest: "{{ basslinemnk_privileged_dir }}/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
    - change-hostname
    - collect-debug-logs
    - read-update-log
    - update
    - update-video-settings

- name: store passwordless sudo paths
  set_fact:
    sudo_paths:
      - /sbin/shutdown
      - /usr/sbin/service basslinemnk-updater start
      - "{{ basslinemnk_privileged_dir }}/change-hostname"
      - "{{ basslinemnk_privileged_dir }}/collect-debug-logs"
      - "{{ basslinemnk_privileged_dir }}/read-update-log"
      - "{{ basslinemnk_privileged_dir }}/update"
      - "{{ basslinemnk_privileged_dir }}/update-video-settings"

- name: enable basslinemnk to execute a whitelist of commands as sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ basslinemnk_user }} ALL=(ALL) NOPASSWD: {{ sudo_paths | join(', ') }}"
    regexp: "^{{ basslinemnk_user }}"
    validate: sudo /usr/sbin/visudo -cf %s

- name: create BasslineMnk folder
  file:
    path: "{{ basslinemnk_dir }}"
    state: directory
    owner: "{{ basslinemnk_user }}"
    group: "{{ basslinemnk_group }}"

- name: get BasslineMnk repo
  git:
    repo: "{{ basslinemnk_repo }}"
    dest: "{{ basslinemnk_dir }}"
    version: "{{ basslinemnk_repo_branch }}"
    accept_hostkey: yes
  notify:
    - restart BasslineMnk service

- name: find absolute path to python3
  shell: realpath $(which python3)
  register: realpath_python3
  changed_when: false

- name: save absolute path to python3
  set_fact:
    python3_abs_path: "{{ realpath_python3.stdout }}"

- name: create BasslineMnk virtualenv
  pip:
    virtualenv: "{{ basslinemnk_dir }}/venv"
    virtualenv_command: "{{ python3_abs_path }} -m venv venv"
    requirements: "{{ basslinemnk_dir }}/requirements.txt"
    extra_args: "{{ basslinemnk_pip_args }}"
  notify:
    - restart BasslineMnk service

- name: create BasslineMnk app settings
  template:
    src: basslinemnk-app-settings.cfg.j2
    dest: "{{ basslinemnk_app_settings_file }}"
    owner: "{{ basslinemnk_user }}"
    group: "{{ basslinemnk_group }}"
  notify:
    - restart BasslineMnk service
  tags:
    - app-settings

- name: fix BasslineMnk folder permissions
  file:
    path: "{{ basslinemnk_dir }}"
    state: directory
    owner: "{{ basslinemnk_user }}"
    group: "{{ basslinemnk_group }}"
    recurse: yes
  # TODO: Figure out why this fails idempotency otherwise.
  tags:
    - molecule-idempotence-notest

- name: install BasslineMnk as a service
  template:
    src: basslinemnk.systemd.j2
    dest: /lib/systemd/system/basslinemnk.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload BasslineMnk systemd config
    - restart BasslineMnk service
  tags:
    - systemd-config

- name: enable systemd BasslineMnk service file
  systemd:
    name: basslinemnk
    enabled: yes

- name: install basslinemnk-updater as a service
  template:
    src: basslinemnk-updater.systemd.j2
    dest: /lib/systemd/system/basslinemnk-updater.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - reload basslinemnk updater systemd config
