---
- name: reload BasslineMnk systemd config
  systemd:
    name: basslinemnk
    daemon_reload: yes

- name: restart BasslineMnk service
  service:
    name: basslinemnk
    state: restarted

- name: reload basslinemnk updater systemd config
  systemd:
    name: basslinemnk-updater
    daemon_reload: yes
    # Never run automatically.
    enabled: no
