#!/bin/bash

# Reads the basslinemnk-updater systemd log and cuts out the junk content.

# Exit on first error.
set -e

# Treat undefined environment variables as errors.
set -u

sudo journalctl -u basslinemnk-updater \
  | grep basslinemnk-update-svc \
  | sed -E 's/^.*basslinemnk-update-svc\[[0-9]+\]: //g'
