#!/usr/bin/env bash

# Echo commands to stdout.
set -x

# Treat undefined environment variables as errors.
set -u

# Exit on first error.
set -e

curl \
  --silent \
  --show-error \
  https://raw.githubusercontent.com/bassline-mnk/basslinemnk/master/quick-install | \
    bash -
